### ISSUE TITLE
Assertion snippets

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/atom-ava#1]
Assertions: https://github.com/sindresorhus/ava#assertions
Docs: https://atom.io/docs/latest/using-atom-snippets

I'm thinking the `prefix` should be `t<name>`, so `tis`, `tsame`, etc.
## 

Could be easily adapted from the Sublime plugin if https://github.com/sindresorhus/sublime-ava/issues/1 is closed before this one.

**Comment by sindresorhus** [comment]
// @sotojuan In case this is something you'd be interested in doing ;) No worries if not.

**Comment by sotojuan** [comment]
I'll definitely give it a shot, though I am busy these few days (but definitely by the end of the week). Thanks for the mention!

**Comment by sindresorhus** [comment]
No rush at all :)

**Comment by SamVerschueren** [comment]
https://github.com/SamVerschueren/vscode-ava/pull/2

Feedback more then welcome!

**Comment by sotojuan** [comment]
I'm not sure what the best practices for snippets are, but I personally like really short ones. For example, for `t.notSame` I'd do `tns`. That said, I could see the argument for `tnotsame`. What about `pass` or `fail`? Again, for me it's quicker to do `tp` or `tf` but that may be too short (?).

**Comment by SamVerschueren** [comment]
Not sure for Atom and Sublime, but in VS Code, when typing `tf`, it shows an auto-complete box with the first match selected. And what about `t.false`. That's `tf` as well :).

![screen shot 2016-02-16 at 08 09 45](https://cloud.githubusercontent.com/assets/1913805/13069395/b8454aa4-d484-11e5-854d-76020a2c1a9c.png)

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/atom-ava/commit/bd1ce093049f67bf7cb86587a556a21bf54142d5
