### ISSUE TITLE
README: wrong keyboard shortcuts

### ISSUE THREAD

**Issue by GramParallelo** [sindresorhus/atom-ava#21]
The shortcuts use <kbd>A</kbd> not <kbd>R</kbd> 

In a project, choose the Ava: Run command in the Command Palette or press Ctrl Alt R to run the tests. Choose Ava: Run File or press Ctrl Alt Shift R to only run the current test file. Press Esc to close the AVA panel.

**Comment by sindresorhus** [comment]
Thanks for reporting :)
